repos:
  - repo: local
    hooks:
      - id: lint
        name: Ruff Lint
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false

      - id: format
        name: Ruff Format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false

      - id: typecheck
        name: Mypy Typecheck
        entry: make typecheck
        language: system
        types: [python]
        pass_filenames: false
