name: Prepare Next Version
description: Bump the project to its next non-final version and push the change

inputs:
  ebump-arguments:
    description: Arguments to pass to ebump
    required: false
    default: patch beta

outputs:
  version:
    description: Prepared next project version
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version to next patch beta
      shell: bash
      run: uvx ebump ${{ inputs.ebump-arguments }}

    - name: Get version
      id: version
      shell: bash
      run: |
        VERSION=$(uvx ebump)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Commit next version preparation
      shell: bash
      run: |
        git add -A
        git commit -m "Prepare next version (${{ steps.version.outputs.version }}) [skip ci]"
        git push origin main
